[package]
name = "compose"
version = "0.1.0"
edition = "2024"

[dependencies]
typst = "0.14.2"
typst-kit = "0.14.2"
typst-library = "0.14.2"
typst-render = "0.14.2"
cxx = "1.0.194"
cxx-qt = { path = "../cxx-qt/crates/cxx-qt/" }
cxx-qt-lib = { path = "../cxx-qt/crates/cxx-qt-lib/", features = ["full"] }

[build-dependencies]
cxx-qt-build = { path = "../cxx-qt/crates/cxx-qt-build/" }
